name: Create Release

on: 
  release:
    types: [ published ]

env:
  ZIP_FILENAME: "pf2e_compendium_chn"
  PACKAGE_CONTENT: "module.json babele.js compendium/ npc/"
  PACKAGE_ID: 1807


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Substitute the Manifest and Download URLs in the module.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'module.json'
      env:
        version: ${{github.event.release.tag_name}}
        url: https://github.com/${{github.repository}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
        download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/${{env.ZIP_FILENAME}}.zip
        changelog: https://github.com/${{github.repository}}/releases/tag/${{github.event.release.tag_name}}

    # Rename and remove files
    - name: Tidy files
      id: tidy-files
      run: rm zh-CN/___.json && mv zh-CN compendium

    # Create a zip file with all files required by the module to add to the release
    - name: Create Artifact
      id: build-zip
      run: zip -r $ZIP_FILENAME.zip $PACKAGE_CONTENT

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: ${{ github.event.release.name }}
        draft: false
        prerelease: false
        artifacts: './module.json, ./${{env.ZIP_FILENAME}}.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}

